#title: Select all users
#comment: Selects all resources that are of type tto:User
#comment: ?korisnik is the only variable
#tags: 1 graph pattern, 1 variable
#color: ex-green


select ?korisnik where {
  ?korisnik rdf:type tto:User .
}
